title: Artin Spiridonoff
description: Research Scientist
# theme: jekyll-theme-cayman
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - resume.md
  - articles.md

# Your Links
social_links:
  linkedin: artins
  github: spiridonoff
  scholar: YaCCwp8AAAAJ&hl=en