title: Artin Spiridonoff
description: Research Scientist
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

feed:
  path: false

markdown: kramdown
kramdown:
  math_engine: mathjax

header_pages:
  - index.md
  - resume.md
  - articles.md

# Your Links
social_links:
  linkedin: artins
  github: spiridonoff
  scholar: YaCCwp8AAAAJ

